usethis::use_build_ignore("devtools_history.R")
usethis::use_build_ignore("dependencies.R")
usethis::use_vignette("README")
usethis::use_package("stats")
usethis::use_package("ggplot2")
usethis::use_package("gridExtra")
usethis::use_package("kableExtra")
usethis::use_package("stringr")
